### ISSUE TITLE
timestamp with timezone support

### ISSUE THREAD

**Issue by a16** [FORTH-ICS-INSPIRE/artemis-web#103]
**Describe the bug**
Some of the values related with timezone are incorrect. I belive that it should be displayed in my local time(Asia/Tokyo), because the page describes `Times are shown in your local time zone`.
But it seems they are hardcoded. 
https://github.com/FORTH-ICS-INSPIRE/artemis-web/blob/master/apps/artemis-web/pages/dashboard.tsx#L113-L115
https://github.com/FORTH-ICS-INSPIRE/artemis-web/blob/master/apps/artemis-web/pages/hijacks.tsx#L541-L544

**Affected Component(s)**
- [ ] Back-End (Node.js, Next.js)
- [x] Front-End (React.js)
- [ ] Theming (CSS, React theme)
- [ ] Build System 
- [ ] Docs

**To Reproduce**
1. Change local timezone in your OS.
2. Go to /dashbord (, /bgpupdates, or /hijacks).
3. See time values in the table. they should be still GMT+2.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [Mac OS]
 - Browser [chrome]
 - Version [91.0.4472.114]

**Additional context**

**Comment by a16** [comment]
Thanks for the fix, But timestamp values in the table are still incorrect. For example, Last Update, Time Detected in Hijacks table.

![screenshot_2021-06-26_8 39 56](https://user-images.githubusercontent.com/5094724/123494733-d5aa2e00-d65b-11eb-9262-a3582467c40a.jpg)

**Comment by CuriouzK0d3r** [comment]
Thanks for reporting this! We are working at this now :)
