### ISSUE TITLE
Protecting API against too many requests

### ISSUE THREAD

**Issue by marcgweg** [FORTH-ICS-INSPIRE/artemis-web#121]
While testing on https://artemis01.sidn.nl/signup I found that there’s no rate limit implemented or CAPTCHA, in this way I can make multiple accounts
Impact:
the attacker can make for example 1 M request that lead to fill your DB with fake accounts .
Step to Reproduce
1. Go to this link and fill up the form
https://artemis01.sidn.nl/signup
or send this request to your Burp Suite Intruder
Code:
POST /api/auth/signup HTTP/1.1
Host: artemis01.sidn.nl
Cookie: sid=1m1mGQmjMEkQIr0KFpUFl
User-Agent: Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Accept: /
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: https://artemis01.sidn.nl/signup
Content-Type: application/json
Origin: https://artemis01.sidn.nl
Content-Length: 169
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Te: trailers
Connection: close
{“email”:“pusakal+6@wearehackerone.com”,“name”:“gonzx”,“password”:“Gonz@2828",“_csrf”:“GtpTUSd7-ElI51zJ0Z55Cdxc5mTa138TESyc.blNjEilJPmqhR53hYHhdA661HhOc9Ebngy89uX5Dq4U”}
2. Add the email in scope to brute force then start the attack
If you will get a 200 status it means the account is successfully created
Recommendation:
To fix this issue, you could implement an timeout after a number of requests in a period of time to return “429 Too Many Requests” when making multiple requests in a short period of time

**Comment by vkotronis** [comment]
Closed with https://github.com/FORTH-ICS-INSPIRE/artemis-web/pull/126
