### ISSUE TITLE
Mouse hover over ASNs does not yield AS info

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis-web#145]
**Describe the bug**
Mouse hovering over the ASNs in the different tables does not seem to work anymore. Not sure when it broke,
needs checking.

**Affected Component(s)**
- [ ] Back-End (Node.js, Next.js)
- [X] Front-End (React.js)
- [ ] Theming (CSS, React theme)
- [ ] Build System 
- [ ] Docs

**To Reproduce**
1. Mouse hover over an ASN. No info is displayed.

**Expected behavior**
AS info should be properly displayed.

**Screenshots**

**System (please complete the following information):**

**Additional context**
N/A

**Comment by CuriouzK0d3r** [comment]
solved in a previous pr
