### ISSUE TITLE
Button update bug on Hijacks screen

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis-web#167]
When I change the selector for "Mark as Resolved" -> "Delete Hijack", it doesn't actually change. but if I do it two times, it does update and change.

**Affected Component(s)**
- [ ] Back-End (Node.js, Next.js)
- [x] Front-End (React.js)
- [ ] Theming (CSS, React theme)
- [ ] Build System 
- [ ] Docs

**To Reproduce**
1. Go to the hijacks page (with active hijacks listed)
2. Select a hijack/or page
3. Pick the mark as resolved button, and change it to another state.
4. It won't change.
5. Pick the same option again, it works.

**Expected behavior**
Should work on the first selection.

**Screenshots**

<img width="520" alt="Screen Shot 2022-12-08 at 10 59 00 AM" src="https://user-images.githubusercontent.com/503771/206519682-09ebf8ea-86ea-4b11-a873-b0987756c99c.png">

**System (please complete the following information):**
 - OS: RHEL8 / docker 
 - Browser Chrome / Firefox
 - Version 108.0.5359.94 / 107.0.1 (64-bit)

**Additional context**

**Comment by vkotronis** [comment]
@CuriouzK0d3r could you take a look here? This is a general problem on this selection menu.
