### ISSUE TITLE
Add CSRF token for forms/APIs

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis-web#28]

**Comment by vkotronis** [comment]
@slowr could you elaborate on this issue so that Alexandros knows what is required? E.g., with some examples?

**Comment by slowr** [comment]
What?
https://portswigger.net/web-security/csrf/tokens

Why? 
https://www.securecoding.com/blog/csrf-attacks/

How? 
https://www.npmjs.com/package/next-csrf
https://medium.com/@valentijnnieman_79984/apollo-next-js-authentication-and-csrf-protection-4d897b9a703f
