### ISSUE TITLE
Implement Hijack page

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis-web#38]
@vkotronis can you add a screenshot of the hijack page? 

This is the code from old frontend
https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/frontend/webapp/render/templates/main/hijack.htm

**Comment by vkotronis** [comment]
![Screenshot_2020-11-18 ARTEMIS - Hijack(1)](https://user-images.githubusercontent.com/1815007/99553331-b2811700-29c6-11eb-95ba-3eb2b26acd62.png)
