### ISSUE TITLE
Add view more on bgp and hijack table

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis-web#39]
@vkotronis can you add a screenshot from the expanded bgp update and the more link on hijacks table?

**Comment by vkotronis** [comment]
Expanded BGP update (I have pressed on the green "+' button on the right side):
![Screenshot_2020-11-18 ARTEMIS - BGP Updates](https://user-images.githubusercontent.com/1815007/99552929-3c7cb000-29c6-11eb-9a52-167194cd5476.png)

Pressing the more link on the hijacks table redirects to the hijack page
![Screenshot_2020-11-18 ARTEMIS - Hijacks](https://user-images.githubusercontent.com/1815007/99553047-5d450580-29c6-11eb-8452-46553759fc50.png)
![Screenshot_2020-11-18 ARTEMIS - Hijack](https://user-images.githubusercontent.com/1815007/99553079-68983100-29c6-11eb-9a09-73d0312f2e62.png)

:
