### ISSUE TITLE
Fix issues with frontend when using it with artemis

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis-web#45]
If you download this:
https://github.com/FORTH-ICS-INSPIRE/artemis/tree/new-frontend

and run `docker-compose build` and then `docker-compose up` you run artemis with the new frontend.

Some issues that came up:

Wrong fields; RPKI seems to be hijack key, timestamps not showing in correct format
![image](https://user-images.githubusercontent.com/3428023/100267566-ef638580-2f53-11eb-966a-d06b183e9200.png)

Uptime is counted in hours
![image](https://user-images.githubusercontent.com/3428023/100267650-1326cb80-2f54-11eb-9e39-b43ab6dec09b.png)

Stats does not use the same names as artemis and there is `view_index_all_stats` at bottom
![image](https://user-images.githubusercontent.com/3428023/100267750-3d788900-2f54-11eb-8c34-e30bad495f2d.png)

BGP Updates are not loaded
![image](https://user-images.githubusercontent.com/3428023/100267790-4a957800-2f54-11eb-853c-c683b8eb680a.png)

**Comment by vkotronis** [comment]
Update: same instructions, but you need to use: https://github.com/FORTH-ICS-INSPIRE/artemis/tree/modularization-new-frontend 

Detailed instructions:
1. Clone ARTEMIS https://github.com/FORTH-ICS-INSPIRE/artemis locally and checkout the `modularization-new-frontend` branch.
2. `cd` into the artemis dir and do (to copy default configs to the correct location):
   ```
   mkdir -p local_configs && \
   mkdir -p local_configs/backend && \
   mkdir -p local_configs/monitor && \
   mkdir -p local_configs/frontend && \
   cp -rn backend-services/configs/* local_configs/backend && \
   cp -rn monitor-services/configs/* local_configs/monitor && \
   cp -rn frontend/webapp/configs/* local_configs/frontend
   ```
3. in the same dir, add the frontend submodule pointing to your repo:
   ```
   git submodule add git@github.com:FORTH-ICS-INSPIRE/artemis-web frontend/
   ```

You can test any version you like under frontend.
The above steps you do them only once.

Then, and whenever you want to run (first pull your code under frontend):
```
docker-compose build frontend
docker-compose up -d
```
