### ISSUE TITLE
Auto-logout upon session exp should redirect to login page

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis-web#91]
**Describe the bug**
I have noticed the following behavior: if I leave the UI open for some time (e.g., on the system page), it automatically logs me out but silently. I.e., I can edit stuff but they have no effect. Could you somehow enforce redirection to the login page upon auto-logout? Otherwise the user understands that his session has expired only after refreshing, which is unusual (redirection should be async upon session expiration).

**Affected Component(s)**
- [X] Back-End (Node.js, Next.js)
- [X] Front-End (React.js)
- [ ] Theming (CSS, React theme)
- [ ] Build System 
- [ ] Docs

**To Reproduce**

**Expected behavior**
Auto-redirection to login page

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by vkotronis** [comment]
Optional: if feasible, please add an .env var to make the expiration time configurable (related to https://github.com/FORTH-ICS-INSPIRE/artemis/issues/486)

**Comment by CuriouzK0d3r** [comment]
> Optional: if feasible, please add an .env var to make the expiration time configurable (related to [FORTH-ICS-INSPIRE/artemis#486](https://github.com/FORTH-ICS-INSPIRE/artemis/issues/486))

Easy peasy
